site_name: Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  logo:   assets/TextFlex-logo.png
  favicon: assets/favicon.png
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent:  bleu
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: yellow
      accent: yellow

  markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

  plugins:
  - glightbox

extra:
  social:
    - icon: simple/dribbble
      link: https://dribbble.com/BlooDlust
    - icon: simple/behance
      link: https://www.behance.net/sharklotfi
    - icon: simple/linkedin
      link: https://www.linkedin.com/in/lotfi-jilal-0118bb165/

copyright: Copyright &copy; 2024 Lotfi Jilal





