site_name: Documentation
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  logo:   assets/TextFlex-logo.png
  favicon: assets/favicon.png
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: black
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: yellow
      accent: lime*

  markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption

  plugins:
  - glightbox






